create table if not exists hotel_settings (hotel_id text primary key, quiet_from int not null default 1290, quiet_to int not null default 480, nudge_from int not null default 1020, nudge_to int not null default 1260, offer_gap_hours int not null default 3, offers_per_day int not null default 2, updated_at timestamptz not null default now(), updated_by text);
create table if not exists dept_hours (id uuid primary key default gen_random_uuid(), hotel_id text not null, dept text not null, open_time text, close_time text, weekend_open_time text, weekend_close_time text, closed_days text not null default '', out_of_hours text, active boolean not null default true, updated_at timestamptz not null default now(), updated_by text, unique (hotel_id, dept));
create table if not exists hotel_profile (hotel_id text primary key, check_in_time text, check_out_time text, front_desk_phone text, emergency_phone text, wifi_name text, wifi_password text, breakfast_hours text, breakfast_place text, address text, parking text, pets text, smoking text, late_checkout text, early_checkin text, currency text, languages text, notes text, updated_at timestamptz not null default now(), updated_by text);
create table if not exists spa_rules (hotel_id text primary key, advance_notice_mins int not null default 120, first_appointment text, last_appointment text, medical_to_human boolean not null default true, cancellation text, age_rule text, notes text, updated_at timestamptz not null default now(), updated_by text);
create table if not exists hotel_services (id uuid primary key default gen_random_uuid(), hotel_id text not null, name text not null, price text, unit text, hours text, dept text, how text, active boolean not null default true, sort_order int not null default 0, updated_at timestamptz not null default now(), updated_by text);
create index if not exists hotel_services_hotel_idx on hotel_services (hotel_id);
create table if not exists offers (id uuid primary key default gen_random_uuid(), hotel_id text not null, guest_phone text not null, item_id text not null, item_name text not null, dept text not null, price numeric not null default 0, reason text, basis text, status text not null default 'proposed', proposed_at timestamptz not null default now(), offered_at timestamptz, resolved_at timestamptz, revenue numeric not null default 0, order_ref text);
create index if not exists offers_hotel_guest_idx on offers (hotel_id, guest_phone, proposed_at desc);
create index if not exists offers_hotel_status_idx on offers (hotel_id, status, proposed_at desc);
